// <auto-generated />
namespace Elearn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initalModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initalModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202207280947375_initalModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
